/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pipeline_branchpredictor_TAGESCL_TAGESCLInvoker */

#ifndef _Included_pipeline_branchpredictor_TAGESCL_TAGESCLInvoker
#define _Included_pipeline_branchpredictor_TAGESCL_TAGESCLInvoker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pipeline_branchpredictor_TAGESCL_TAGESCLInvoker
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pipeline_branchpredictor_TAGESCL_TAGESCLInvoker_initialize
  (JNIEnv *, jobject);

/*
 * Class:     pipeline_branchpredictor_TAGESCL_TAGESCLInvoker
 * Method:    predict
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_pipeline_branchpredictor_TAGESCL_TAGESCLInvoker_predict
  (JNIEnv *, jobject, jlong);

/*
 * Class:     pipeline_branchpredictor_TAGESCL_TAGESCLInvoker
 * Method:    train
 * Signature: (JIZZJ)V
 */
JNIEXPORT void JNICALL Java_pipeline_branchpredictor_TAGESCL_TAGESCLInvoker_train
  (JNIEnv *, jobject, jlong, jint, jboolean, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
